services:
  mlflow:
    image: ghcr.io/mlflow/mlflow:latest
    command: mlflow ui --host 0.0.0.0 --port 5000 --backend-store-uri file:/mlruns
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns

  api:
    build: ./api
    environment:
      - MODEL_PATH=/app/models/latest
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro
    depends_on:
      - mlflow